Repository PHPSP/phpsp.org.br, pull requests merged in 2019-07, with the labels that each got.

#54 Adiciona um sitemap.xml ao projeto
  app/Site/EventHandlers/AfterBuild/GenerateSitemap.php
  app/Site/EventHandlers/JigsawHandlerInterface.php
  bootstrap.php
  composer.json
  composer.lock
Labels: enhancement

#55 Melhora os sitemaps
  app/Site/EventHandlers/AfterBuild/GenerateSitemap.php
  composer.json
  composer.lock
  config.php
  source/robots.txt
Labels: enhancement

#57 Add link[rel=canonical] to head.blade.php partial
  README.md
  source/_partials/layout/head.blade.php
Labels: enhancement, has PR already

#60 Arruma o setup do docker e o CI
  composer.lock
  docker/web/Dockerfile
Labels: bug

#59 Add Darkmira Tour 2018 post
  source/_posts/como-foi-o-darkmira-tour-2018.md
  source/assets/images/posts/como-foi-o-darkmira-tour-2018/darkmira2018.jpg
  source/assets/images/posts/como-foi-o-darkmira-tour-2018/ecossistema_elk.jpg
  source/assets/images/posts/como-foi-o-darkmira-tour-2018/fornecendo_contexto.jpg
  source/assets/images/posts/como-foi-o-darkmira-tour-2018/lei_de_demeter.jpg
Labels: new-post
